### ISSUE TITLE
Map speed up

### ISSUE THREAD

**Issue by MengLeZhang** [DanOlner/ShinyMapEssentials#3]
Speed up the leaflet map

resources:
- https://stackoverflow.com/questions/62700258/leaflet-in-another-tab-not-updated-with-leafletproxy-before-visiting-tab/62701468#62701468

**Comment by DanOlner** [comment]
Ways to indicate a load is occurring. Map would be more tolerable if user knows something's definitely happening in the slower bits e.g. if London's loading LSOAs and frontiers. https://stackoverflow.com/questions/49488228/how-to-show-spinning-wheel-or-busy-icon-while-waiting-in-shiny

**Comment by DanOlner** [comment]
Hmm, interestingly, there's an R mapbox option! Mapbox is likely a LOT faster, but don't know how easy to integrate. It's used (I think) by e.g. the 2021 Census atlas: https://www.ons.gov.uk/census/maps

https://stackoverflow.com/questions/74634958/how-to-add-a-mapbox-layer-using-r-shiny-and-mapboxer

**Comment by MengLeZhang** [comment]
To be fair it's quite fast (72ms) so I'll clsoe this one
